#!/bin/sh

# Selity - When virtual hosting becomes scalable
#
# Copyright (C) 2006-2010 by isp Control Panel - http://ispcp.net
# Copyright (C) 2010-2012 by internet Multi Server Control Panel - http://i-mscp.net
# Copyright (C) 2012-2014 by Selity - http://selity.org
#
# The contents of this file are subject to the Mozilla Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://www.mozilla.org/MPL/
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is "ispCP ω (OMEGA) a Virtual Hosting Control Panel".
#
# The Initial Developer of the Original Code is ispCP Team.
# Portions created by Initial Developer are Copyright (C) 2006-2010 by
# isp Control Panel. All Rights Reserved.
#
# Portions created by the i-MSCP Team are Copyright (C) 2010-2011 by
# internet Multi Server Control Panel. All Rights Reserved.
#
# Portions created by the Selity Team are Copyright (C) 2012 by Selity.
# All Rights Reserved.
#
# The Selity Home Page is:
#
#    http://selity.org
#

# description:
#
# creates the main selity.pot file out of any found strings in the php files
#
# Warning: This script will remove any strings which aren't present in the GUI
# php files, this means dynamic strings or strings out of the database will
# ignored.
#

set -e

if [ $1 ] && [ -d $1 ]; then
	GUI=${1}
else
	GUI=../../gui
fi

if [ ! -f ${GUI}/public/index.php ]; then
	if [ -f ${GUI}/gui/index.php ]; then
		GUI=${GUI}/gui/
	fi
fi

if [ ! -f ${GUI}/public/index.php ]; then
	echo "${GUI} isn't a valid gui/ location."
	exit 1
fi

# PHP files
/usr/bin/xgettext \
--foreign-user \
--language=PHP \
-d "Selity" \
--keyword="tr" \
--no-location \
${GUI}/library/selity/*.php \
${GUI}/public/*.php \
${GUI}/public/*/*.php \
--from-code=utf-8 \
-p ../po \
-o "Selity.pot"

sed --in-place '/#. Please ignore this entry/d' ../po/Selity.pot
sed --in-place 's/msgid "encoding"/#. Please ignore this entry\nmsgid "encoding"/' ../po/Selity.pot

exit 0
